services:
  client:
    container_name: "gymbroClient"
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # depends_on:
    #   - server
    restart: unless-stopped
