services:
  server:
    build:
      context: ./server
    container_name: "gymbroServer"
    ports:
      - "8080:8080"
    restart: unless-stopped

  client:
    container_name: "gymbroClient"
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    restart: unless-stopped
